events {}
http {
    include mime.types;
    server {
        listen ${PORT};
        root /var/www/html;
        index index.php;

        location / {
            try_files $uri $uri/ @rewrite;
        }

        location @rewrite {
            rewrite ^/mentions-legales$ /mentions-legales.php last;
            rewrite ^/([a-z0-9-]+)$ /index.php?$query_string last;
        }

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }
    }
}
